#server
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
  servlet:
    context-path: /


#spring
spring:
  datasource:
    url: jdbc:mysql:///bj520?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    resources:  #\u6B64\u914D\u7F6E\u662F\u653E\u884CCss\u9759\u6001\u8D44\u6E90
      static-locations:
        - classpath:/static/

mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/*.xml

#lOG
logging:
  level:
    com.cy: DEBUG
